all:
	g++ main.cpp -fopenmp -Wall -O3 -std=c++11 -o main
	#g++ main_negsamp1.cpp -fopenmp -Wall -O3 -std=c++11 -o main_negsamp1
	#g++ main_negsamp2.cpp -fopenmp -Wall -O3 -std=c++11 -o main_negsamp2
	g++ main_negsamp3.cpp -fopenmp -Wall -O3 -std=c++11 -o main_negsamp3
	#g++ -g main.cpp -fopenmp -Wall -std=c++11 -o main
	#g++ -g main_negsamp1.cpp -fopenmp -Wall -std=c++11 -o main_negsamp1
	#g++ -g main_negsamp2.cpp -fopenmp -Wall -std=c++11 -o main_negsamp2
	#g++ main_negsamp3.cpp -fopenmp -Wall -std=c++11 -o main_negsamp3

clean:
	rm -f *.o main
	rm -f *.o main_negsamp1
	rm -f *.o main_negsamp2
	rm -f *.o main_negsamp3
